#!/usr/bin/env bash
#MISE description="Install tools and configure git hooks"
set -euo pipefail

mise install --locked
mise run setup:mdformat
MISE_ENV=development mise install --locked --locked
MISE_ENV=development mise exec -- lefthook install
