apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-hetzner
  annotations:
    meta.crossplane.io/maintainer: Mihai Lemnaru <mihai.lmnr@proton.me>
    meta.crossplane.io/source: github.com/miaits/provider-hetzner
    meta.crossplane.io/license: Apache-2.0 
    meta.crossplane.io/description: |
      Crossplane provider for Hetzner Cloud
    meta.crossplane.io/readme: |
      `provider-hetzner` is a crossplane infrastructure provider for 
      [Hetzner Cloud](https://hetzner.com/cloud). 

      It is based on the Terraform Hetzner provider. Read the 
      [readme](https://github.com/miaits/provider-hetzner/blob/main/README.md)
      for instructions.      
spec:
  capabilities:
    - SafeStart
